# Generated by Django 3.2 on 2021-04-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='icon_image',
            field=models.ImageField(default='profile/default_icon.jpg', upload_to='profile/icon_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(default='profile/default_header.jpg', upload_to='profile/header_pics'),
        ),
    ]
