# Generated by Django 3.2 on 2021-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210430_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, default='', max_length=140, null=True),
        ),
    ]
