# Generated by Django 3.2 on 2021-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, default='Hello', max_length=140, null=True),
        ),
    ]
